---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре -  название, рейтинг, цена со скидкой и без нее         #Уточнение из задания для разработчика 
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - После добавления товара в корзину, пользователь остается на странице каталога           #Требование из задания для разработчика 
  - Пользователь должен иметь возможность удалить товар из корзины
  - При оформления заказа пользователь должен перейти на страницу оплаты заказа 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть SPA-приложением 
implicit:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизации на сайте с использованием индивидуального логина и пароля
  - Пользователь должен добавить товар в корзину                                           #Чтобы выполнить требование 10
  - Для оплаты заказа необходимо чтобы на сайте была реализована функция оплаты заказа     #Чтобы выполнить требование 11
  - Пользователь должен иметь личный кабинет с историей покупок и личными данными (ФИО,тел, почта, привязка к платежным картам)                                       #Чтобы выполнить неявное требование 24
 
