---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизации на сайте с использованием индивидуального логина и пароля
  - На сайте у пользователя должен быть личный кабинет с историей покупок и личными данными
  - При оформлении заказа предоставить пользователю способ оплаты
  
