---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре -  название, рейтинг, цена со скидкой и без нее         #Уточнение из задания для разработчика 
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - После добавления товара в корзину, пользователь остается на странице каталога                        #Требование из задания для разработчика 
  - Пользователь должен иметь возможность удалить товар из корзины, находясь на странице корзины         #Требование из задания для разработчика 
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге, находясь на странице корзины    #Требование из задания для разработчика 
  - При оформления заказа пользователь должен перейти на страницу оплаты заказа                           #Требование из задания для разработчика
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть SPA-приложением                                                                       #Требование из задания для разработчика 
  - Корзина будет хранится в сессии браузера                                                               #Требование из задания для разработчика 
implicit:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизации на сайте с использованием индивидуального логина и пароля

  - Пользователь должен иметь личный кабинет с историей покупок и личными данными (ФИО,тел, почта, привязка к платежным картам)                                    



    #Требование из задания для разработчика - требования для разработсика в первой части описания , то что написано сплошным текстом 
